version: "2"

services:
  server:
    env_file:
      - .env
    image: python:3.7
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - db
    ports:
      - 3000:3000
    command: python src/server.py

  dbdata:
    image: busybox
    volumes:
      - /var/lib/postgresql/data
  db:
    image: postgres:9.4
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes_from:
      - dbdata

  testserver:
    env_file: .env
    image: python:3.7
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - testdb
    ports:
      - 5053:5053
    environment:
      APPLICATION_PORT: 5053
      APPLICATION_DB_CONTAINER: testdb
    command: python -m pytest test/

  testdb:
    image: postgres:9.4
