name: API

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create .env
        run: |
        cd api
        mv .env.example .env
    - name: Install server
      run: make server.install
    - name: Upgrade database
      run: make database.Upgrade
    - name: Run tests
      run: make test
