name: API

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create .env
      run: mv .env.example .env
      working-directory: ./api
    - name: Install server
      run: make server.install
      working-directory: ./api
    - name: Upgrade database
      run: make database.Upgrade
      working-directory: ./api
    - name: Run tests
      run: make test
      working-directory: ./api
